version: "2"
containers:
- name: vault-server
  image: vault:1.3.4
  shell: /bin/sh
  ports:
  - 8200
  environment:
    SKIP_SETCAP: "true"
    VAULT_ADDR: http://localhost:8200
    VAULT_DEV_ROOT_TOKEN_ID: root
    VAULT_TOKEN: root
  memory: 128
