version: "2"
- name: vault-server
  image: eastern-flight-262517/vault-1-3-2-ent-consul-1-6-3-ent-2
  shell: /bin/bash -l
  environment:
    SKIP_SETCAP: "true"
    VAULT_ADDR: http://localhost:8200
    VAULT_DEV_ROOT_TOKEN_ID: root
    VAULT_TOKEN: root
  machine_type: n1-standard-1
