version: "2"
virtualmachines:
- name: workstation
  image: instruqt-hashicorp/hashistack-0-5-1
  shell: /bin/bash -l
  environment:
    SKIP_SETCAP: "true"
    VAULT_ADDR: http://localhost:8200
    VAULT_DEV_ROOT_TOKEN_ID: root
    VAULT_TOKEN: root
  machine_type: n1-standard-1
